import * as t from "@babel/types";
// @types/babel__generator's default export doesn't resolve cleanly under NodeNext+ESM
// (a known typings/module-resolution friction, not specific to this codebase) — the
// named export `generate` is the same function and resolves without issue.
import { generate } from "@babel/generator";
import type { DesignNode } from "@weavensign/schema";
import prettier from "prettier";
import { renderNode } from "./render-node.js";

const COMPONENT_NAME = "GeneratedDesign";

function wrapInFragmentIfNeeded(elements: t.JSXElement[]): t.JSXElement | t.JSXFragment {
  if (elements.length === 1) {
    return elements[0]!;
  }
  return t.jsxFragment(t.jsxOpeningFragment(), t.jsxClosingFragment(), elements);
}

/**
 * Builds the full Babel AST for one function component wrapping the whole DesignNode
 * tree — one flat component, not one component per container node (a deliberately
 * narrower scope than a fully idiomatic React decomposition, matching
 * renderer-html-css's "one tree in, one output" shape and keeping this renderer's
 * determinism story simple: no naming scheme or cross-component import wiring to keep
 * stable).
 */
function buildComponentAst(roots: DesignNode[]): t.Program {
  const elements = roots.map((node) => renderNode(node)).filter((node): node is t.JSXElement => node !== null);
  const body = wrapInFragmentIfNeeded(elements);

  const fn = t.functionDeclaration(t.identifier(COMPONENT_NAME), [], t.blockStatement([t.returnStatement(body)]));

  const exportDecl = t.exportNamedDeclaration(fn, []);
  t.addComment(exportDecl, "leading", "* Generated by @weavensign/renderer-jsx-tsx. Do not edit directly. ", false);
  return t.program([exportDecl], [], "module");
}

/**
 * Renders a full DesignNode[] tree into a self-contained .tsx source string: one
 * function component, styled via inline `style={{...}}` objects built from the same
 * declaration logic `@weavensign/renderer-html-css` uses for CSS rules (see
 * @weavensign/renderer-shared). Pure and deterministic (context.md §4.7) except for the
 * Prettier formatting pass, which is itself deterministic for a fixed input — same
 * input always produces the same output string. This is the package's public entry
 * point.
 */
export async function renderComponent(roots: DesignNode[]): Promise<string> {
  const program = buildComponentAst(roots);
  const { code } = generate(program);
  // Prettier's format() re-parses `code` with its own babel-ts parser before printing —
  // if this call succeeds, that's already independent proof the generated AST is
  // syntactically valid TSX; a separate "does the output parse" test would only
  // duplicate that check with a second, heavier compiler (caught the one real case this
  // matters for while building this renderer's own golden fixtures: raw JSXText content
  // containing a literal `<` crashed here before render-text.ts switched to a string
  // literal — see that file's doc comment).
  return prettier.format(code, { parser: "babel-ts" });
}
