/** Generated by @weavensign/renderer-jsx-tsx. Do not edit directly. */
export function GeneratedDesign() {
  return (
    <div
      key="8:10"
      title="Frame 2"
      style={{
        position: "absolute",
        left: "0px",
        top: "100px",
        width: "300px",
        height: "150px",
        backgroundImage: 'url("https://example.com/resolved-photo.png")',
        backgroundSize: "100% 100%",
        overflow: "hidden",
      }}
    ></div>
  );
}
