/** Generated by @weavensign/renderer-jsx-tsx. Do not edit directly. */
export function GeneratedDesign() {
  return (
    <div
      key="8:10"
      title="Frame 2"
      style={{
        position: "absolute",
        left: "0px",
        top: "100px",
        width: "300px",
        height: "150px",
        backgroundColor: "rgb(229, 229, 229)",
        backgroundImage:
          "repeating-linear-gradient(45deg, rgb(200, 200, 200) 0px, rgb(200, 200, 200) 8px, transparent 8px, transparent 16px)",
        overflow: "hidden",
      }}
    ></div>
  );
}
