/** Generated by @weavensign/renderer-jsx-tsx. Do not edit directly. */
export function GeneratedDesign() {
  return (
    <div
      key="frame-1"
      title="Card"
      style={{
        position: "absolute",
        left: "0px",
        top: "0px",
        width: "200px",
        height: "100px",
        backgroundColor: "rgb(255, 255, 255)",
        border: "1px solid rgb(204, 204, 204)",
        borderRadius: "8px",
        overflow: "hidden",
      }}
    >
      <div
        key="text-1"
        style={{
          position: "absolute",
          left: "12px",
          top: "12px",
          width: "176px",
          height: "20px",
          textAlign: "left",
        }}
      >
        <span
          style={{
            fontFamily: "Inter",
            fontWeight: "600",
            fontStyle: "normal",
            fontSize: "16px",
            letterSpacing: "0px",
            textDecoration: "none",
            textTransform: "none",
          }}
        >
          {"Hello & <world>"}
        </span>
      </div>
      <div
        key="vector-1"
        style={{
          position: "absolute",
          left: "12px",
          top: "40px",
          width: "24px",
          height: "24px",
        }}
      >
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="rgb(51, 102, 230)"
        >
          <path d="M0 0 L24 0 L24 24 L0 24 Z" fillRule="nonzero" />
        </svg>
      </div>
    </div>
  );
}
