/** Generated by @weavensign/renderer-jsx-tsx. Do not edit directly. */
export function GeneratedDesign() {
  return (
    <div
      key="28:86"
      style={{
        position: "absolute",
        left: "0px",
        top: "0px",
        width: "auto",
        height: "auto",
        textAlign: "left",
      }}
    >
      <span
        style={{
          fontFamily: "Raleway",
          fontWeight: "500",
          fontStyle: "normal",
          fontSize: "16.11px",
          letterSpacing: "0px",
          textDecoration: "none",
          textTransform: "none",
          lineHeight: "18.92px",
        }}
      >
        {"Home"}
      </span>
    </div>
  );
}
